//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* eslint-disable */
// ReSharper disable InconsistentNaming

export class Client {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        this.http = http ? http : window as any;
        this.baseUrl = baseUrl ?? "http://localhost:8080";
    }

    /**
     * @return OK
     */
    exportToExcel(body: Shipment): Promise<void> {
        let url_ = this.baseUrl + "/shipment/exportToExcel";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processExportToExcel(_response);
        });
    }

    protected processExportToExcel(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @param noticol (optional) 
     * @param hazardous (optional) 
     * @param status (optional) 
     * @param destination (optional) 
     * @param startDate (optional) 
     * @param endDate (optional) 
     * @param deliveryNote (optional) 
     * @return OK
     */
    searchShipments(noticol: string | undefined, hazardous: boolean | undefined, status: string | undefined, destination: string | undefined, startDate: string | undefined, endDate: string | undefined, deliveryNote: string | undefined): Promise<Shipment[]> {
        let url_ = this.baseUrl + "/shipment/searchShipments?";
        if (noticol === null)
            throw new globalThis.Error("The parameter 'noticol' cannot be null.");
        else if (noticol !== undefined)
            url_ += "noticol=" + encodeURIComponent("" + noticol) + "&";
        if (hazardous === null)
            throw new globalThis.Error("The parameter 'hazardous' cannot be null.");
        else if (hazardous !== undefined)
            url_ += "hazardous=" + encodeURIComponent("" + hazardous) + "&";
        if (status === null)
            throw new globalThis.Error("The parameter 'status' cannot be null.");
        else if (status !== undefined)
            url_ += "status=" + encodeURIComponent("" + status) + "&";
        if (destination === null)
            throw new globalThis.Error("The parameter 'destination' cannot be null.");
        else if (destination !== undefined)
            url_ += "destination=" + encodeURIComponent("" + destination) + "&";
        if (startDate === null)
            throw new globalThis.Error("The parameter 'startDate' cannot be null.");
        else if (startDate !== undefined)
            url_ += "startDate=" + encodeURIComponent("" + startDate) + "&";
        if (endDate === null)
            throw new globalThis.Error("The parameter 'endDate' cannot be null.");
        else if (endDate !== undefined)
            url_ += "endDate=" + encodeURIComponent("" + endDate) + "&";
        if (deliveryNote === null)
            throw new globalThis.Error("The parameter 'deliveryNote' cannot be null.");
        else if (deliveryNote !== undefined)
            url_ += "deliveryNote=" + encodeURIComponent("" + deliveryNote) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "*/*"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processSearchShipments(_response);
        });
    }

    protected processSearchShipments(response: Response): Promise<Shipment[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(Shipment.fromJS(item));
            }
            else {
                result200 = null as any;
            }
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<Shipment[]>(null as any);
    }

    /**
     * @return OK
     */
    getShipmentById(noticol: string): Promise<Shipment> {
        let url_ = this.baseUrl + "/shipment/getShipmentById?";
        if (noticol === undefined || noticol === null)
            throw new globalThis.Error("The parameter 'noticol' must be defined and cannot be null.");
        else
            url_ += "noticol=" + encodeURIComponent("" + noticol) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "*/*"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetShipmentById(_response);
        });
    }

    protected processGetShipmentById(response: Response): Promise<Shipment> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = Shipment.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<Shipment>(null as any);
    }
}

export class Delivery implements IDelivery {
    id?: string;
    orderNumber?: string;
    quantity?: number;
    price?: number;
    itemNumber?: string;
    manufacturer?: string;

    [key: string]: any;

    constructor(data?: IDelivery) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.id = _data["id"];
            this.orderNumber = _data["orderNumber"];
            this.quantity = _data["quantity"];
            this.price = _data["price"];
            this.itemNumber = _data["itemNumber"];
            this.manufacturer = _data["manufacturer"];
        }
    }

    static fromJS(data: any): Delivery {
        data = typeof data === 'object' ? data : {};
        let result = new Delivery();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["id"] = this.id;
        data["orderNumber"] = this.orderNumber;
        data["quantity"] = this.quantity;
        data["price"] = this.price;
        data["itemNumber"] = this.itemNumber;
        data["manufacturer"] = this.manufacturer;
        return data;
    }
}

export interface IDelivery {
    id?: string;
    orderNumber?: string;
    quantity?: number;
    price?: number;
    itemNumber?: string;
    manufacturer?: string;

    [key: string]: any;
}

export class HandlingUnit implements IHandlingUnit {
    id?: string;
    weight?: number;
    breadth?: number;
    length?: number;
    height?: number;
    volume?: number;
    type?: string;
    stackable?: boolean;
    noticol?: string;
    deliveries?: Delivery[];

    [key: string]: any;

    constructor(data?: IHandlingUnit) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.id = _data["id"];
            this.weight = _data["weight"];
            this.breadth = _data["breadth"];
            this.length = _data["length"];
            this.height = _data["height"];
            this.volume = _data["volume"];
            this.type = _data["type"];
            this.stackable = _data["stackable"];
            this.noticol = _data["noticol"];
            if (Array.isArray(_data["deliveries"])) {
                this.deliveries = [] as any;
                for (let item of _data["deliveries"])
                    this.deliveries!.push(Delivery.fromJS(item));
            }
        }
    }

    static fromJS(data: any): HandlingUnit {
        data = typeof data === 'object' ? data : {};
        let result = new HandlingUnit();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["id"] = this.id;
        data["weight"] = this.weight;
        data["breadth"] = this.breadth;
        data["length"] = this.length;
        data["height"] = this.height;
        data["volume"] = this.volume;
        data["type"] = this.type;
        data["stackable"] = this.stackable;
        data["noticol"] = this.noticol;
        if (Array.isArray(this.deliveries)) {
            data["deliveries"] = [];
            for (let item of this.deliveries)
                data["deliveries"].push(item ? item.toJSON() : undefined as any);
        }
        return data;
    }
}

export interface IHandlingUnit {
    id?: string;
    weight?: number;
    breadth?: number;
    length?: number;
    height?: number;
    volume?: number;
    type?: string;
    stackable?: boolean;
    noticol?: string;
    deliveries?: Delivery[];

    [key: string]: any;
}

export class Shipment implements IShipment {
    noticol?: string;
    hazardous?: boolean;
    destination?: string;
    status?: string;
    deliveryNote?: string;
    startDate?: string;
    endDate?: string;
    actualDate?: string;
    handlingUnit?: HandlingUnit;

    [key: string]: any;

    constructor(data?: IShipment) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.noticol = _data["noticol"];
            this.hazardous = _data["hazardous"];
            this.destination = _data["destination"];
            this.status = _data["status"];
            this.deliveryNote = _data["deliveryNote"];
            this.startDate = _data["startDate"];
            this.endDate = _data["endDate"];
            this.actualDate = _data["actualDate"];
            this.handlingUnit = _data["handlingUnit"] ? HandlingUnit.fromJS(_data["handlingUnit"]) : undefined as any;
        }
    }

    static fromJS(data: any): Shipment {
        data = typeof data === 'object' ? data : {};
        let result = new Shipment();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["noticol"] = this.noticol;
        data["hazardous"] = this.hazardous;
        data["destination"] = this.destination;
        data["status"] = this.status;
        data["deliveryNote"] = this.deliveryNote;
        data["startDate"] = this.startDate;
        data["endDate"] = this.endDate;
        data["actualDate"] = this.actualDate;
        data["handlingUnit"] = this.handlingUnit ? this.handlingUnit.toJSON() : undefined as any;
        return data;
    }
}

export interface IShipment {
    noticol?: string;
    hazardous?: boolean;
    destination?: string;
    status?: string;
    deliveryNote?: string;
    startDate?: string;
    endDate?: string;
    actualDate?: string;
    handlingUnit?: HandlingUnit;

    [key: string]: any;
}

export class ApiException extends Error {
    override message: string;
    status: number;
    response: string;
    headers: { [key: string]: any; };
    result: any;

    constructor(message: string, status: number, response: string, headers: { [key: string]: any; }, result: any) {
        super();

        this.message = message;
        this.status = status;
        this.response = response;
        this.headers = headers;
        this.result = result;
    }

    protected isApiException = true;

    static isApiException(obj: any): obj is ApiException {
        return obj.isApiException === true;
    }
}

function throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): any {
    if (result !== null && result !== undefined)
        throw result;
    else
        throw new ApiException(message, status, response, headers, null);
}